### ISSUE TITLE
osint minion is failing on splitting ' used by '

### ISSUE THREAD

**Issue by gdbassett** [vz-risk/Verum#42]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Users/v685573/Documents/Development/Verum/minions/osint_bambenekconsulting_com.py", line 217, in minion
    df = pd.concat([df, pd.DataFrame(df.context.str.split(' used by ',1).tolist(), columns = ['key','threat'])], axis=1)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 255, in __init**
    copy=copy)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 367, in _init_ndarray
    return create_block_manager_from_blocks([values.T], [columns, index])
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 3230, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 3211, in construction_error
    passed,implied))
ValueError: Shape of passed values is (0, 0), indices imply (2, 0)

---

It appears the intel list has changed their format.  Example new file at: https://s3.amazonaws.com/gabe1/c2-masterlist.txt

**Comment by gdbassett** [comment]
Added v2 of minion to import new format.
